###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Cesar Uagusto Diaz",
  "userName": "cdizss",
  "password": "cdiaz123",
  "role": "ADMIN",
  "email": "cdiaz@gmail"
  }


###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Maria Estela Lopez",
  "userName": "mlopez",
  "password": "mlopez123",
  "role": "USER",
  "email": "marialopez@gmail"
  }